# Generated by Django 4.1.1 on 2022-11-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisionalTests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prov_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
