# Generated by Django 4.1.1 on 2022-11-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provisionalTests', '0002_prov_questions_delete_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_one', models.CharField(max_length=100)),
                ('choice_two', models.CharField(max_length=100)),
                ('choice_three', models.CharField(max_length=100)),
                ('choice_four', models.CharField(max_length=100)),
                ('toQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisionalTests.prov_questions')),
            ],
        ),
    ]
