# Generated by Django 4.1.1 on 2022-11-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provisionalTests', '0003_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prov_questions',
            old_name='hotel_Main_Img',
            new_name='Q_Image',
        ),
    ]
