# Generated by Django 4.1.1 on 2022-12-11 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provisionalTests', '0004_rename_hotel_main_img_prov_questions_q_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='choice_four',
        ),
        migrations.AddField(
            model_name='prov_questions',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
