# Generated by Django 4.1.1 on 2022-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisionalTests', '0005_remove_answers_choice_four_prov_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prov_questions',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
